# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       osc

# >> macros
# << macros

# YAML OUT OF DATE AND MESSES UP SPEC GENERATION

%{!?python_sitelib: %define python_sitelib %(%{__python} -c "from distutils.sysconfig import get_python_lib; print get_python_lib()")}
Summary:    OpenSUSE Build Service Commander
Version:    0.151.2.skytree47
Release:    1
Group:      Development/Tools/Other
License:    GPL v2 or later
BuildArch:  noarch
URL:        http://www.gitorious.org/opensuse/osc
Source0:    osc-%{version}.tar.bz2
Source100:  osc.yaml
Patch0:     0001-ppc64le-can-build-ppc64-in-KVM.patch
Patch1:     0002-create_submit_request-fix-return-value-when-falling-.patch
Patch2:     0003-Pass-threads-option-to-obs-build.patch
Patch3:     0004-change_request_state-manual-xml-parsing-is-error-pro.patch
Patch4:     0005-do_buildhistory-split-args-on-slash.patch
Patch5:     0006-Pass-disk-swap-logfile-options-to-obs-build-also-for.patch
Patch6:     0007-Add-support-for-searches-for-groups-with-i-b-and-m.patch
Patch7:     0008-Add-missing-tags-for-maintainer-bugowner.patch
Patch8:     0009-use-group-prefix-instead-of-group-like-in-other-comm.patch
Patch9:     0010-add-support-for-buildtime-source-service-mode.patch
Patch10:     0011-do_deleterequest-fix-help-text.patch
Patch11:     0012-show-possible-used-incident-projects-on-maintained-c.patch
Patch12:     0013-updated-distributions-that-are-used-in-the-new-proje.patch
Patch13:     0014-do_build-added-trust-all-projects-option.patch
Patch14:     0015-Don-t-filter-out-b-v-f-r-in-logfiles.patch
Patch15:     0016-avoid-buffering-stdout-output-on-pipes-bnc-930137.patch
Patch16:     0017-changed-commit-22b272f3afc1a3f3b83b764b7745a662bc0aa.patch
Patch17:     0018-README-replaced-mentioning-of-svn-version-with-git-v.patch
Patch18:     0019-added-lock-command-to-lock-a-project-or-package.patch
Patch19:     0020-allow-to-use-osc-chroot-also-with-lxc-build-type.patch
Patch20:     0021-support-acceptinfo-in-maintenance_incident-requests.patch
Patch21:     0022-allow-diffing-of-maintenance-requests.patch
Patch22:     0023-support-target-package-in-accepted-maintenance_incid.patch
Patch23:     0024-fixed-fullfilename-calculation-in-the-Pac-class.patch
Patch24:     0025-fixed-147.patch
Patch25:     0026-Do-not-strip-colon-from-COMP_WORDBREAKS-bnc-915037.patch
Patch26:     0027-Allow-osc-to-be-called-as-isc-and-iosc.patch
Patch27:     0028-Add-sb2install-support-to-osc.patch
Patch28:     0029-Support-osc-copyprj-in-api-by-Islam-Amer.patch
Patch29:     0030-Support-synchronous-copyproj.patch
Patch30:     0031-Add-p-to-copyprj-to-enable-copying-of-prjconf.patch
Patch31:     0032-Add-support-for-rebuild-and-chroot-only-in-build.patch
Patch32:     0033-Add-architecture-and-scheduler-maps.patch
Patch33:     0034-Trap-any-kind-of-exception-during-plugin-parsing-eg-.patch
Patch34:     0035-Fixup-old-style-print-statements.patch
Patch35:     0036-Added-config-options-for-cgit-interoperability.patch
%if 0%{?mandriva_version} < 02010
BuildRequires:  python-urlgrabber
Requires:       python-urlgrabber
%endif
BuildRequires:  python-devel
%if 0%{?mandriva_version}
BuildRequires:  python-rpm
Requires:       python-rpm
%else
BuildRequires:  rpm-python
Requires:       rpm-python
%endif
#
%if 0%{?suse_version}
%if 0%{?suse_version} < 1020
BuildRequires:  python-elementtree
Requires:       python-elementtree
%else
BuildRequires:  python-xml
Requires:       python-xml
%endif
%if 0%{?suse_version} > 1110
BuildArch:      noarch
%endif
%if 0%{?suse_version} > 1000
Recommends:     build >= 2010.05.04
Recommends:     sudo
# These packages are needed for "osc add $URL"
Recommends:     obs-service-recompress
Recommends:     obs-service-set_version
Recommends:     obs-service-tar_scm
Recommends:     obs-service-verify_file
Recommends:     obs-service-download_files
Recommends:     obs-service-format_spec_file
Recommends:     obs-service-source_validator
%endif
%endif
# needed for storing credentials in kwallet/gnome-keyring
%if 0%{?suse_version} > 1000 || 0%{?mandriva_version} || 0%{?mdkversion}
Recommends:     python-keyring
%endif
%if 0%{?rhel_version} && 0%{?rhel_version} < 600
BuildRequires:  python-elementtree
Requires:       python-elementtree
%endif
%if 0%{?centos_version} && 0%{?centos_version} < 600
BuildRequires:  python-elementtree
Requires:       python-elementtree
%endif
%if 0%{?suse_version}%{?mandriva_version}
BuildRequires:  python-m2crypto
Requires:       python-m2crypto > 0.19
%else
BuildRequires:  m2crypto
Requires:       m2crypto > 0.19
%endif
%{!?python_sitelib: %define python_sitelib %(python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()")}

%description
Commandline client for the openSUSE Build Service.

See http://en.opensuse.org/openSUSE:OSC , as well as
http://en.opensuse.org/openSUSE:Build_Service_Tutorial for a general
introduction.

%prep
%setup -q -n src

# 0001-ppc64le-can-build-ppc64-in-KVM.patch
%patch0 -p1
# 0002-create_submit_request-fix-return-value-when-falling-.patch
%patch1 -p1
# 0003-Pass-threads-option-to-obs-build.patch
%patch2 -p1
# 0004-change_request_state-manual-xml-parsing-is-error-pro.patch
%patch3 -p1
# 0005-do_buildhistory-split-args-on-slash.patch
%patch4 -p1
# 0006-Pass-disk-swap-logfile-options-to-obs-build-also-for.patch
%patch5 -p1
# 0007-Add-support-for-searches-for-groups-with-i-b-and-m.patch
%patch6 -p1
# 0008-Add-missing-tags-for-maintainer-bugowner.patch
%patch7 -p1
# 0009-use-group-prefix-instead-of-group-like-in-other-comm.patch
%patch8 -p1
# 0010-add-support-for-buildtime-source-service-mode.patch
%patch9 -p1
# 0011-do_deleterequest-fix-help-text.patch
%patch10 -p1
# 0012-show-possible-used-incident-projects-on-maintained-c.patch
%patch11 -p1
# 0013-updated-distributions-that-are-used-in-the-new-proje.patch
%patch12 -p1
# 0014-do_build-added-trust-all-projects-option.patch
%patch13 -p1
# 0015-Don-t-filter-out-b-v-f-r-in-logfiles.patch
%patch14 -p1
# 0016-avoid-buffering-stdout-output-on-pipes-bnc-930137.patch
%patch15 -p1
# 0017-changed-commit-22b272f3afc1a3f3b83b764b7745a662bc0aa.patch
%patch16 -p1
# 0018-README-replaced-mentioning-of-svn-version-with-git-v.patch
%patch17 -p1
# 0019-added-lock-command-to-lock-a-project-or-package.patch
%patch18 -p1
# 0020-allow-to-use-osc-chroot-also-with-lxc-build-type.patch
%patch19 -p1
# 0021-support-acceptinfo-in-maintenance_incident-requests.patch
%patch20 -p1
# 0022-allow-diffing-of-maintenance-requests.patch
%patch21 -p1
# 0023-support-target-package-in-accepted-maintenance_incid.patch
%patch22 -p1
# 0024-fixed-fullfilename-calculation-in-the-Pac-class.patch
%patch23 -p1
# 0025-fixed-147.patch
%patch24 -p1
# 0026-Do-not-strip-colon-from-COMP_WORDBREAKS-bnc-915037.patch
%patch25 -p1
# 0027-Allow-osc-to-be-called-as-isc-and-iosc.patch
%patch26 -p1
# 0028-Add-sb2install-support-to-osc.patch
%patch27 -p1
# 0029-Support-osc-copyprj-in-api-by-Islam-Amer.patch
%patch28 -p1
# 0030-Support-synchronous-copyproj.patch
%patch29 -p1
# 0031-Add-p-to-copyprj-to-enable-copying-of-prjconf.patch
%patch30 -p1
# 0032-Add-support-for-rebuild-and-chroot-only-in-build.patch
%patch31 -p1
# 0033-Add-architecture-and-scheduler-maps.patch
%patch32 -p1
# 0034-Trap-any-kind-of-exception-during-plugin-parsing-eg-.patch
%patch33 -p1
# 0035-Fixup-old-style-print-statements.patch
%patch34 -p1
# 0036-Added-config-options-for-cgit-interoperability.patch
%patch35 -p1
# >> setup
# << setup

%build
# the PATH hack/rewrite is needed for Fedora 20 builds, because /bin
# is a symlink to /usr/bin and /bin precedes /usr/bin in PATH
# => a "wrong" interpreter line ("#!/bin/python") is constructed
# ("wrong", because no package provides "/bin/python").
PATH="/usr/bin:$PATH" CFLAGS="%{optflags}" python setup.py build

%install
python setup.py install --prefix=%{_prefix} --root=%{buildroot}
ln -s osc-wrapper.py %{buildroot}/%{_bindir}/osc
mkdir -p %{buildroot}%{_localstatedir}/lib/osc-plugins
install -Dm0644 dist/complete.csh %{buildroot}%{_sysconfdir}/profile.d/osc.csh
%if 0%{?suse_version}
install -Dm0644 dist/complete.sh %{buildroot}%{_sysconfdir}/bash_completion.d/osc.sh
%else
install -Dm0644 dist/complete.sh %{buildroot}%{_sysconfdir}/profile.d/osc.sh
%endif
%if 0%{?suse_version} > 1110
install -Dm0755 dist/osc.complete %{buildroot}%{_prefix}/lib/osc/complete
%else
install -Dm0755 dist/osc.complete %{buildroot}%{_libdir}/osc/complete
%endif

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc AUTHORS README TODO NEWS COPYING
%{_bindir}/osc*
%{python_sitelib}/*
%config %{_sysconfdir}/profile.d/osc.csh
%if 0%{?suse_version}
%config %{_sysconfdir}/bash_completion.d/osc.sh
%else
%config %{_sysconfdir}/profile.d/osc.sh
%endif
%dir %{_localstatedir}/lib/osc-plugins
%{_mandir}/man1/osc.*
%if 0%{?suse_version} > 1110
%{_prefix}/lib/osc
%else
%{_libdir}/osc
%endif

%changelog
